/*
 Find the Difference
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
*/

char findTheDifference(char * s, char * t){
    int lens=strlen(s);
    int lent=strlen(t);
    int cnts=0,cntt=0;

    for(int i=0;i<lens;i++)
    {
        cnts=cnts + (s[i] - 'a');
    }

    for(int i=0;i<lent;i++)
    {
        cntt=cntt + (t[i] - 'a');
    }

    int diff=cntt - cnts;
    char letter= diff + 'a';
    return letter;
}
